version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '03:00'
      timezone: 'UTC'

    open-pull-requests-limit: 5

    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

    pull-request-branch-name:
      separator: '/'

    labels:
      - 'dependencies'
      - 'npm'

    reviewers:
      - 'nayandas69'

    assignees:
      - 'nayandas69'

    rebase-strategy: 'auto'
    versioning-strategy: 'increase'

    allow:
      - dependency-type: 'direct'

    groups:
      nuxt:
        patterns:
          - 'nuxt'
          - '@nuxt/*'

      vue:
        patterns:
          - 'vue'
          - '@vue/*'

      testing:
        patterns:
          - 'vitest'
          - '@vue/test-utils'
          - '@nuxt/test-utils'
          - 'happy-dom'

      formatting:
        patterns:
          - 'prettier'

      types:
        patterns:
          - '@types/*'

  - package-ecosystem: 'github-actions'
    directory: '/'

    schedule:
      interval: 'monthly'
      time: '04:00'
      timezone: 'UTC'

    commit-message:
      prefix: 'chore(ci)'
      include: 'scope'

    pull-request-branch-name:
      separator: '/'

    labels:
      - 'ci'
      - 'github-actions'

    reviewers:
      - 'nayandas69'

    assignees:
      - 'nayandas69'

    rebase-strategy: 'auto'
